# Generated by Django 5.0.6 on 2024-08-24 14:43

import datetime
import django.db.models.deletion
import django.utils.timezone
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('CDE_PROD', models.CharField(default='AR001', max_length=20, primary_key=True, serialize=False)),
                ('LIB_PROD', models.CharField(default='produit', max_length=250)),
                ('PRI_ACHT_PROD', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('PRI_VENT_PROD', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('TYPE_PROD', models.CharField(default='produit', max_length=50)),
                ('COND_PROD', models.IntegerField(default=0)),
                ('STOCK_PROD', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AvoirLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NUM_LOT', models.CharField(max_length=30)),
                ('CDE_PROD', models.CharField(max_length=30)),
                ('DATE_PER', models.DateField()),
                ('QTE_LOT', models.IntegerField()),
                ('PRIX_ACHT_LOT', models.DecimalField(decimal_places=4, max_digits=10)),
                ('PRIX_VENT_LOT', models.DecimalField(decimal_places=4, max_digits=10)),
                ('SUSPENDU', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('N_DEMANDE', models.AutoField(primary_key=True, serialize=False)),
                ('DATE_DEMANDE', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(default='usser1', max_length=255)),
                ('adresse', models.CharField(default='usser1', max_length=50)),
                ('phone', models.CharField(default='usser1', max_length=50)),
                ('job', models.CharField(default='usser1', max_length=50)),
                ('password', models.CharField(default='myCompany123', max_length=50)),
                ('department', models.CharField(default='informatique', max_length=255)),
                ('date_hired', models.DateTimeField(default=datetime.datetime(2024, 1, 1, 0, 0))),
                ('salaire', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('formation_date', models.DateField()),
                ('duration', models.DurationField()),
                ('location', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='FormationAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('formation_date', models.DateField()),
                ('duration', models.DurationField()),
                ('location', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='FormationInterssant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('CDE_FOUR', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('NOM_FOUR', models.CharField(max_length=100)),
                ('ADR_FOUR', models.TextField()),
                ('TEL_PORT', models.CharField(max_length=30)),
                ('TEL_BUR', models.CharField(max_length=15)),
                ('FAX_FOUR', models.CharField(default='mail', max_length=50)),
                ('MAIL_FOUR', models.CharField(default='mail', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequestAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_user', models.CharField(default='username', max_length=255)),
                ('number_of_days', models.IntegerField()),
                ('reason', models.TextField()),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(default='title', max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('admin_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('ID_UNIQUE', models.AutoField(primary_key=True, serialize=False)),
                ('NOM', models.CharField(max_length=100)),
                ('PRENOM', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('NUM_COM', models.AutoField(primary_key=True, serialize=False)),
                ('DATE_COM', models.DateTimeField()),
                ('OBSE', models.CharField(default='produit', max_length=200)),
                ('ETAT', models.CharField(default='produit', max_length=50)),
                ('CDE_FOUR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_days', models.IntegerField()),
                ('reason', models.TextField()),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(default='title', max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('related_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminActionDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('response_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('related_user', models.CharField(default='username1', max_length=100)),
                ('admin_demande', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.leaverequest')),
            ],
        ),
        migrations.CreateModel(
            name='ActionDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('response_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('related_user', models.CharField(default='username1', max_length=100)),
                ('demande', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.leaverequest')),
            ],
        ),
        migrations.CreateModel(
            name='ligne_distrubition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nlot', models.CharField(max_length=100)),
                ('date_peremption', models.DateField()),
                ('qte_lot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_dist', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_dem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='users.demande')),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('QTE_COM', models.IntegerField()),
                ('PRIX_COM', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('TOT_COM', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('CDE_PROD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.article')),
                ('NUM_COM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='users.commande')),
            ],
        ),
        migrations.CreateModel(
            name='LigneDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cde_prod', models.CharField(max_length=100)),
                ('num_dem', models.CharField(max_length=100)),
                ('qte_dem', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qte_dist', models.DecimalField(decimal_places=2, max_digits=10)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='users.demande')),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('NUM_LIV', models.AutoField(primary_key=True, serialize=False)),
                ('ARR_LIV', models.DateField()),
                ('DAT_LIV', models.DateField()),
                ('ETAT_LIV', models.CharField(default='En Cours', max_length=50)),
                ('CDE_FOUR', models.CharField(max_length=30)),
                ('NUM_COM', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.commande')),
            ],
        ),
        migrations.CreateModel(
            name='LivraisonLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CDE_PROD', models.CharField(max_length=30)),
                ('QTE_LIV', models.IntegerField(default=1)),
                ('PRIX_LIV', models.DecimalField(decimal_places=3, default=0.0, max_digits=10, validators=[users.models.validate_price])),
                ('line_created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('NUM_LOT', models.CharField(max_length=30)),
                ('DATE_PER', models.DateField()),
                ('QTE_COM', models.IntegerField(default=1)),
                ('ARRIVAGE_LIV', models.IntegerField(default=1)),
                ('NUM_LIV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='users.livraison')),
            ],
        ),
        migrations.AddField(
            model_name='demande',
            name='ID_UNIQUE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('id_card', models.CharField(blank=True, max_length=20, null=True)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(limit_choices_to={'is_superuser': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
