# Generated by Django 5.0.6 on 2024-08-30 22:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actiondemande',
            name='demande',
        ),
        migrations.RemoveField(
            model_name='adminactiondemande',
            name='admin_demande',
        ),
        migrations.DeleteModel(
            name='Employe',
        ),
        migrations.DeleteModel(
            name='Formation',
        ),
        migrations.DeleteModel(
            name='FormationAdmin',
        ),
        migrations.DeleteModel(
            name='FormationInterssant',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='related_user',
        ),
        migrations.DeleteModel(
            name='LeaveRequestAdmin',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RenameField(
            model_name='lignecommande',
            old_name='PRIX_COM',
            new_name='PRIX_COM_UNITAIRE',
        ),
        migrations.AddField(
            model_name='article',
            name='DATE_PROD',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='ligne_distrubition',
            name='code_prod',
            field=models.CharField(default='prod1', max_length=100),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='QTE_COM_TOTALE',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ActionDemande',
        ),
        migrations.DeleteModel(
            name='AdminActionDemande',
        ),
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
