# Generated by Django 5.0.6 on 2024-08-31 09:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_patient_adresse_patient_date_naissance_patient_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='DATE_SUBMIT',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
