# Generated by Django 5.0.6 on 2024-09-02 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_patient_date_submit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignedemande',
            name='num_dem',
        ),
    ]
